[package]
name = "grid_gossip"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
futures = "0.3"
tokio = { version = "1", features = ["full"] }
libp2p = { version = "0.52", features = ["async-std", "gossipsub", "mdns", "noise", "macros", "tcp", "yamux"] }
libp2p-quic = { version = "0.8.0-alpha", features = ["async-std"] }
async-trait = "0.1"
async-std = { version = "1.12", features = ["attributes"] }

[[bin]]
name = "node_0"
path = "src/node_0.rs"

[[bin]]
name = "node_1"
path = "src/node_1.rs"
